### ISSUE TITLE
main_couple.py run error

### ISSUE THREAD

**Issue by PlantMaize** [Plant-Root-Soil-Interactions-Modelling/CRootBox#3]
Traceback (most recent call last):
  File "main_couple.py", line 14, in <module>
    from mpl_toolkits.mplot3d import Axes3D
  File "/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/__init__.py", line 4, in <module>
    from matplotlib.externals import six
ImportError: No module named 'matplotlib.externals'

**Comment by xiaoranzhou** [comment]
It is a version problem, if you are using ubuntu you can remove package `python3-matplotlib` by 
`sudo apt-get purge python3-matplotlib`
