### ISSUE TITLE
running code on server error

### ISSUE THREAD

**Issue by PlantMaize** [Plant-Root-Soil-Interactions-Modelling/CRootBox#4]
got an error when running on server
`Soil upper boundary potential  -23.4221311342
Read 5 root type parameters 
No root system parameters found, using default tap root system 
Traceback (most recent call last):
  File "main_couple.py", line 95, in <module>
    fig1 = plt.figure() # Prepare output 
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/pyplot.py", line 534, in figure
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/backend_bases.py", line 170, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/backends/backend_tkagg.py", line 1049, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1871, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable`

**Comment by xiaoranzhou** [comment]
because you don't have a display.
put `-X` on your ssh command line or you can use Xming [http://www.straightrunning.com/XmingNotes/](url) if you are using windows.
